---
###
### Controller
###
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-controller-api
  namespace: {{.Values.namespace}}
  labels:
    {{.Values.controllerComponentLabel}}: controller
    {{.Values.controllerNamespaceLabel}}: {{.Values.namespace}}
  annotations:
    {{.Values.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.linkerdVersion) .Values.cliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.Values.controllerComponentLabel}}: controller
  ports:
  - name: http
    port: 8085
    targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{.Values.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.linkerdVersion) .Values.cliVersion}}
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: Linkerd
    app.kubernetes.io/version: {{default .Values.linkerdVersion .Values.controllerImageVersion}}
    {{.Values.controllerComponentLabel}}: controller
    {{.Values.controllerNamespaceLabel}}: {{.Values.namespace}}
  name: linkerd-controller
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.controller.replicas}}
  selector:
    matchLabels:
      {{.Values.controllerComponentLabel}}: controller
      {{.Values.controllerNamespaceLabel}}: {{.Values.namespace}}
  {{- if .Values.enablePodAntiAffinity }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  {{- end }}
  template:
    metadata:
      annotations:
        {{.Values.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.linkerdVersion) .Values.cliVersion}}
        {{- with .Values.podAnnotations }}{{ toYaml . | trim | nindent 8 }}{{- end }}
      labels:
        {{.Values.controllerComponentLabel}}: controller
        {{.Values.controllerNamespaceLabel}}: {{.Values.namespace}}
        {{.Values.workloadNamespaceLabel}}: {{.Values.namespace}}
        {{- with .Values.podLabels }}{{ toYaml . | trim | nindent 8 }}{{- end }}
    spec:
      {{- if .Values.tolerations -}}
      {{- include "linkerd.tolerations" . | nindent 6 }}
      {{- end -}}
      {{- include "linkerd.node-selector" . | nindent 6 }}
      {{- if .Values.enablePodAntiAffinity -}}
      {{- $local := dict "component" "controller" "label" .Values.controllerComponentLabel -}}
      {{- include "linkerd.pod-affinity" $local | nindent 6 -}}
      {{- end }}
      containers:
      - args:
        - public-api
        - -destination-addr=linkerd-dst.{{.Values.linkerdNamespace}}.svc.{{.Values.clusterDomain}}:8086
        - -controller-namespace={{.Values.namespace}}
        - -log-level={{.Values.controllerLogLevel}}
        - -cluster-domain={{.Values.clusterDomain}}
        {{- if .Values.prometheusUrl }}
        - -prometheus-url={{.Values.prometheusUrl}}
        {{- else }}
        - -prometheus-url=http://linkerd-prometheus.{{.Values.namespace}}.svc.{{.Values.clusterDomain}}:9090
        {{- end }}
        image: {{.Values.controller.image.name}}:{{default .Values.linkerdVersion .Values.controller.image.tag}}
        imagePullPolicy: {{.Values.controller.image.pullPolicy}}
        livenessProbe:
          httpGet:
            path: /ping
            port: 9995
          initialDelaySeconds: 10
        name: public-api
        ports:
        - containerPort: 8085
          name: http
        - containerPort: 9995
          name: admin-http
        readinessProbe:
          failureThreshold: 7
          httpGet:
            path: /ready
            port: 9995
        {{- if .Values.controller.resources -}}
        {{- include "partials.resources" .Values.controller.resources | nindent 8 }}
        {{- end }}
        securityContext:
          runAsUser: {{.Values.controller.UID}}
      serviceAccountName: linkerd-controller
