---
###
### Linkerd Viz Extension Namespace
###
---
kind: Namespace
apiVersion: v1
metadata:
  name: {{.Values.namespace}}
  labels:
    linkerd.io/extension: linkerd-jaeger
  annotations:
    {{.Values.proxyInjectAnnotation}}: enabled
